[project]
name = "nationalparkagent"
version = "0.1.0"
description = "A national park agent"
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "deepagents>=0.7.14",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "langchain>=1.0.0",
    "langchain-chroma>=1.1.0",
    "langchain-mcp-adapters>=0.3.2",
    "langchain-ollama>=1.0.0",
    "langchain-openrouter>=0.2.8",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.0.0",
    "openai>=3.13.0",
    "pydantic>=2.13.5",
    "pypdf>=6.18.1",
    "python-multipart>=0.0.20",
    "uvicorn>=0.52.4",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.vercel]
entrypoint = "src.nationalparkagent.main:app"
